services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./config/inter/.env
    volumes:
      - ./data:/app/data
      - ./media:/app/media
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped
